version = 1

test_patterns = [
  "**/*_test.go",
  "**/*.spec.js"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/monetr/monetr"]

exclude_patterns = ["**/*.min.js"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile",
    "Dockerfile.api",
    "Dockerfile.ui",
    "Dockerfile.work",
  ]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "flow"

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
