workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(.tmp)/'
      when: never
    - when: always

stages:
  - Dependencies
  - Build Binary
  - Test
  - Schema Preflight
  - Schema
  - Documentation
  - Coverage
  - Build Container
  - Publish Container

variables:
  GO111MODULE: 'on'
  GOFLAGS: '-mod=vendor'

Go Dependencies:
  needs: [ ]
  stage: Dependencies
  image: containers.harderthanitneedstobe.com/golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - go mod vendor
  cache:
    key: go-${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: push

JS Dependencies:
  needs: [ ]
  stage: Dependencies
  image: containers.harderthanitneedstobe.com/node:15.12.0-buster
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - yarn install --no-lockfile # Will use my npm proxy/registry allowing for faster pulling of dependencies.
  cache:
    key: js-${CI_COMMIT_SHA}
    paths:
      - ./node_modules
    policy: push

Build:
  needs:
    - "Go Dependencies"
  stage: Build Binary
  image: containers.harderthanitneedstobe.com/golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - go build -o ./bin/rest-api-${GOARCH} github.com/harderthanitneedstobe/rest-api/v0/cmd/api
  cache:
    key: go-${CI_COMMIT_SHA}
    paths:
      - ./bin
      - ./vendor
    policy: pull-push

Go Tests:
  needs:
    - "Go Dependencies"
  services:
    - name: containers.harderthanitneedstobe.com/postgres:13
      alias: postgres
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: api-testing
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: Test
  image: containers.harderthanitneedstobe.com/golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - make apply-schema-ci
  script:
    - make test
  cache:
    key: go-${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull
  artifacts:
    name: "$CI_COMMIT_SHA-test-coverage"
    paths:
      - ./coverage.txt
    expire_in: 7 days

PostgreSQL Tests:
  needs: [ ]
  stage: Test
  services:
    - name: containers.harderthanitneedstobe.com/pgtest:latest
      alias: postgres
  image:
    name: containers.harderthanitneedstobe.com/pgtest:latest
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: postgres
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - sleep 5
    - |
      for file in $CI_PROJECT_DIR/schema/*; do
        psql -q -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -f $file
      done
    - psql -q -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -c "CREATE EXTENSION pgtap;"
    - pg_prove -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -f ./tests/pg/*.sql

Build Database Image:
  needs: [ ]
  stage: Schema Preflight
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  variables:
    VAULT_AUTH_ROLE: harder-rest-api-shorty
  secrets:
    DOCKER_CONFIG_JSON:
      vault: containers/shorty/docker-config.json@pipelines/harderthanitneedstobe.com
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - ln -s $DOCKER_CONFIG_JSON /kaniko/.docker/config.json
  script:
    - |
      kaniko --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.database \
        --destination shorty.containers.harderthanitneedstobe.com/database-schema-changes:$CI_COMMIT_SHA

Diff Schema PGDiff:
  allow_failure: true
  needs:
    - "Build Database Image"
  stage: Schema
  services:
    - name: shorty.containers.harderthanitneedstobe.com/database-schema-changes:$CI_COMMIT_SHA
      alias: new
    - name: containers.harderthanitneedstobe.com/database-schema-base:latest
      alias: current
  image: containers.harderthanitneedstobe.com/golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  variables:
    POSTGRES_PASSWORD: "password"
    POSTGRES_USER: postgres
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
    GOFLAGS: '' # Clear this flag for this one.
  script:
    - go get github.com/joncrlsn/pgdiff
    - go build -o /usr/local/bin/pgdiff github.com/joncrlsn/pgdiff
    - |
      pgdiff \
        -U $POSTGRES_USER -H current -D $POSTGRES_DB -O "sslmode=disable" -W $POSTGRES_PASSWORD \
        -u $POSTGRES_USER -h new -d $POSTGRES_DB -o "sslmode=disable" -w $POSTGRES_PASSWORD ALL
    - sleep 1000

Diff Schema Migra:
  allow_failure: true
  needs:
    - "Build Database Image"
  stage: Schema
  services:
    - name: shorty.containers.harderthanitneedstobe.com/database-schema-changes:$CI_COMMIT_SHA
      alias: new
    - name: containers.harderthanitneedstobe.com/database-schema-base:latest
      alias: current
  image: containers.harderthanitneedstobe.com/ubuntu:20.04
  tags:
    - k8s:shared
    - arch:amd64
  variables:
    POSTGRES_PASSWORD: "password"
    POSTGRES_USER: postgres
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
    GOFLAGS: '' # Clear this flag for this one.
  script:
    - apt-get install python3-pip
    - pip install migra[pg]

Yeet Coverage:
  needs:
    - "Go Tests"
  environment:
    name: DeepSource
  stage: Coverage
  image: ghcr.io/harderthanitneedstobe/deepsource:v0.1.7-9-gff81369
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - export DEEPSOURCE_DSN=$K8S_SECRET_DEEPSOURCE_DSN
    - deepsource report --analyzer test-coverage --key go --value-file ./coverage.txt
  dependencies:
    - "Go Tests"

Documentation:
  allow_failure: true
  needs:
    - "Go Dependencies"
  stage: Documentation
  image: containers.harderthanitneedstobe.com/golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - mkdir -p /home || true
    - cd /home
    - GO111MODULE=off GOFLAGS="" go get github.com/swaggo/swag/cmd/swag
    - GO111MODULE=off GOFLAGS="" go build -o /usr/local/bin/swag github.com/swaggo/swag/cmd/swag
    - cd $CI_PROJECT_DIR
  script:
    - swag init -d pkg/controller -g controller.go --parseDependency --parseDepth 5 --parseInternal
  cache:
    key: go-${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull
  artifacts:
    name: "$CI_COMMIT_SHA-documentation"
    paths:
      - ./docs
    expire_in: 7 days

Kaniko - REST API:
  needs:
    - "Go Dependencies"
  stage: Build Container
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - kaniko --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push

Kaniko - Work UI:
  allow_failure: true
  needs:
    - "Go Dependencies"
  stage: Build Container
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - kaniko --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.work --no-push

Publish - REST API:
  needs:
    - "Kaniko - REST API"
    - "Go Tests"
  variables:
    VAULT_AUTH_ROLE: harder-rest-api
  secrets:
    DOCKER_CONFIG_JSON:
      vault: containers/push/docker-config.json@pipelines/harderthanitneedstobe.com
  stage: Publish Container
  only:
    refs:
      - main
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - ln -s $DOCKER_CONFIG_JSON /kaniko/.docker/config.json
  script:
    - |
      kaniko --context $CI_PROJECT_DIR \
        --build-arg $CI_COMMIT_SHA \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination ghcr.io/harderthanitneedstobe/rest-api:latest \
        --destination ghcr.io/harderthanitneedstobe/rest-api:$(git rev-parse --short HEAD)  \
        --destination containers.harderthanitneedstobe.com/rest-api:latest \
        --destination containers.harderthanitneedstobe.com/rest-api:$(git rev-parse --short HEAD)

Publish - Work UI:
  needs:
    - "Kaniko - Work UI"
  variables:
    VAULT_AUTH_ROLE: harder-rest-api
  secrets:
    DOCKER_CONFIG_JSON:
      vault: containers/push/docker-config.json@pipelines/harderthanitneedstobe.com
  stage: Publish Container
  only:
    refs:
      - main
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - ln -s $DOCKER_CONFIG_JSON /kaniko/.docker/config.json
  script:
    - |
      kaniko --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile.work \
        --destination ghcr.io/harderthanitneedstobe/work-ui:latest \
        --destination containers.harderthanitneedstobe.com/work-ui:latest

Publish - Database Schema:
  needs:
    - "Build Database Image"
  variables:
    VAULT_AUTH_ROLE: harder-rest-api
  secrets:
    DOCKER_CONFIG_JSON:
      vault: containers/push/docker-config.json@pipelines/harderthanitneedstobe.com
  stage: Publish Container
  only:
    refs:
      - main
  image: containers.harderthanitneedstobe.com/kaniko-ci:latest
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - ln -s $DOCKER_CONFIG_JSON /kaniko/.docker/config.json
  script:
    - |
      kaniko --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile.work \
        --destination containers.harderthanitneedstobe.com/database-schema-base:$CI_COMMIT_SHORT_SHA \
        --destination containers.harderthanitneedstobe.com/database-schema-base:latest
