stages:
  - Dependencies
  - Build Javascript
  - Test Javascript
  - Build Container
  - Publish Container

Fetch Dependencies:
  stage: Dependencies
  image: node:15.10.0-buster
  tags:
    - k8s:shared
  before_script:
    - yarn config set registry https://nexus.elliotcourant.dev/repository/registry.npmjs.org/
  script:
    - yarn install
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./node_modules
    policy: push

Build:
  stage: Build Javascript
  image: node:15.10.0-buster
  tags:
    - k8s:shared
  script:
    - yarn build
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
      - ./node_modules
    policy: pull-push

Test:
  stage: Test Javascript
  image: node:15.10.0-buster
  tags:
    - k8s:shared
  script:
    - yarn test
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./node_modules
    policy: pull

Kaniko:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
    policy: pull

Publish GitHub:
  environment:
    name: GitHub
  stage: Publish Container
  only:
    refs:
      - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"elliotcourant\",\"password\":\"$K8S_SECRET_GITHUB_ACCESS_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination ghcr.io/harderthanitneedstobe/web-ui:latest
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
    policy: pull
