stages:
  - Dependencies
  - Build Binary
  - Test
  - Build Container

variables:
  GO111MODULE: 'on'
  GOFLAGS: '-mod=vendor'

Fetch Dependencies:
  stage: Dependencies
  image: golang:1.15.8
  tags:
    - k8s:shared
  script:
    - go mod vendor
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: push

Build:
  stage: Build Binary
  image: golang:1.15.8
  tags:
    - k8s:shared
  script:
    - go build -o ./bin/rest-api github.com/harderthanitneedstobe/rest-api/v0/cmd/api
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./bin
      - ./vendor
    policy: pull-push

Schema Generation:
  stage: Test
  image: golang:1.15.8
  tags:
    - k8s:shared
  script:
    - make schema
    - make special-tests
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull

Tests:
  services:
    - postgres:13
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: api-testing
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: Test
  image: golang:1.15.8
  tags:
    - k8s:shared
  before_script:
    - make apply-schema-ci
  script:
    - go test -race -v ./...
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull

Kaniko:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.x --no-push
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./bin
    policy: pull
