stages:
  - Dependencies
  - Build Binary
  - Test
  - Build Container
  - Publish Container

variables:
  GO111MODULE: 'on'
  GOFLAGS: '-mod=vendor'

Fetch Dependencies:
  stage: Dependencies
  image: golang:1.16.0
  tags:
    - k8s:shared
    - arch:amd64  
  script:
    - go mod vendor
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: push

Build:
  stage: Build Binary
  image: golang:1.16.0
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - go build -o ./bin/rest-api-${GOARCH} github.com/harderthanitneedstobe/rest-api/v0/cmd/api
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./bin
      - ./vendor
    policy: pull-push

Schema Generation:
  stage: Test
  image: golang:1.16.0
  tags:
    - k8s:shared
  script:
    - make schema
    - make special-tests
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull

Tests:
  services:
    - postgres:13
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: api-testing
    POSTGRES_DB: test-db
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: Test
  image: golang:1.16.0
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - make apply-schema-ci
  script:
    - go test -race -v ./...
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./vendor
    policy: pull

Kaniko - amd64:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./bin
    policy: pull

Publish GitHub:
  environment: GitHub
  stage: Publish Container
  only:
    refs:
      - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"elliotcourant\",\"password\":\"$K8S_SECRET_GITHUB_ACCESS_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination ghcr.io/harderthanitneedstobe/rest-api:latest
