stages:
  - Dependencies
  - Build Javascript
  - Build Container
  - Publish Container

Fetch Dependencies:
  stage: Dependencies
  image: node:15.8.0-buster
  tags:
    - k8s:shared
  script:
    - yarn install
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./node_modules
    policy: push

Build:
  stage: Build Javascript
  image: node:15.8.0-buster
  tags:
    - k8s:shared
  script:
    - yarn build
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
      - ./node_modules
    policy: pull-push

Kaniko:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
    policy: pull

Publish GitLab:
  stage: Publish Container
  only:
    refs:
      - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:latest
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - ./build
    policy: pull
