name: monetr
uiDomainName: localhost:3000
apiDomainName: localhost:4000
allowSignUp: true
enableWebhooks: false
jwt:
  loginJwtSecret: abc123
  registrationJwtSecret: 123abc
postgreSql:
  address: localhost
  port: 5432
  username: postgres
  password: ""
  database: postgres
smtp:
  enabled: false
reCaptcha:
  enabled: false
plaid:
  clientId: "abc123"
  clientSecret: "abc123"
  environment: "https://sandbox.plaid.com"
cors:
  allowedOrigins:
    - "*"
  debug: true
redis:
  enabled: true
  address: localhost
  port: 6379
logging:
  level: trace
