services:
  delve_install:
    image: golang:1.18
    working_dir: /build
    command:
      - go
      - install
      - github.com/go-delve/delve/cmd/dlv@latest
    volumes:
      - delveBinary:/go/bin
  monetr:
    tty: true
    image: cosmtrek/air
    restart: always
    working_dir: /build
    environment:
      air_wd: /build
      MONETR_PLAID_CLIENT_ID: $PLAID_CLIENT_ID
      MONETR_PLAID_CLIENT_SECRET: $PLAID_CLIENT_SECRET
      MONETR_EMAIL_VERIFICATION_TOKEN_SECRET: "abc123"
      MONETR_EMAIL_FORGOT_PASSWORD_TOKEN_SECRET: "123abc"
      MONETR_JWT_LOGIN_SECRET: "qwertyuiop1234567890"
    command:
      - -c
      - /build/air.toml
    links:
      - redis
      - postgres
    ports:
      - 2345:2345
    volumes:
      - ./:/build
      - ./compose/monetr.yaml:/etc/monetr/config.yaml
      - delveBinary:/go/bin
    depends_on:
      mail:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_started
      delve_install:
        condition: service_completed_successfully
  ui:
    tty: true
    image: node:17.5.0
    working_dir: /build
    environment:
      INSECURE_WS: "true"
      NODE_OPTIONS: --openssl-legacy-provider
      IS_COMPOSE: "true"
    volumes:
      - ./:/build
    command:
      - yarn
      - start
  mail:
    image: mailhog/mailhog
    environment:
      MH_CORES_ORIGIN: localhost
      MH_HOSTNAME: localhost
  redis:
    image: redis:6.2.2-alpine
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    tty: true
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./compose/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - monetr
      - ui
      - mail

volumes:
  delveBinary:
