# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/monetr/rest-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccountName:

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: [ ]
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: { }
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/arch: amd64

tolerations: [ ]

affinity: { }

api:
  customEnv: [ ]
  includeSecrets: false
  listenPort: 4000
  metricsPort: 9000
  name: monetr
  uiDomainName: localhost:3000
  apiDomainName: localhost:4000
  allowSignUp: true
  enableWebhooks: false
  beta:
    enableBetaCodes: false
  jwt:
    loginJwtSecret: ""
    registrationJwtSecret: ""
  postgreSql:
    address: localhost
    port: 5432
    username: postgres
    password: ""
    database: postgres
  smtp:
    enabled: false
  sendGrid:
    enabled: false
    apiKey: ""
    templates:
      verifyEmailTemplate: ""
      forgotPasswordTemplate: ""
  reCaptcha:
    enabled: false
    privateKey: ""
    publicKey: ""
    verifyLogin: false
    verifyRegister: false
  plaid:
    clientId: "abc123"
    clientSecret: "abc123"
    environment: "https://sandbox.plaid.com"
    birthdatePrompt: false # Not yet implemented
    enableReturningUserExperience: false
    webhooksEnabled: false
    webhooksDomain: ""
  cors:
    allowedOrigins:
      - "*"
    debug: true
  redis:
    enabled: true
    address: localhost
    port: 6379
    namespace: monetr
  logging:
    level: trace
  sentry:
    enabled: false
    sampleRate: 0.0
    traceSampleRate: 0.0
  stripe:
    enabled: false
    apiKey: ""
    publicKey: ""
    webhooksEnabled: false
    webhooksDomain: ""
    webhookSecret: ""
