replicaCount: 3

image:
  repository: ghcr.io/monetr/monetr
  pullPolicy: Always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets: [ ]

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9000'

serviceAccountName: monetr

service:
  port: 4000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: my.monetr.dog
      paths:
        - path: /
  tls:
    - secretName: my-monetr-dog-tls
      hosts:
        - my.monetr.dog

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

disruption:
  enabled: false
  maxUnavailable: 1
  minAvailable: 1

customEnvFrom:
  - secretRef:
      name: monetr-config-secrets

api:
  name: monetr
  customEnv:
    - name: MONETR_ENVIRONMENT
      value: "my.monetr.dog"
  uiDomainName: my.monetr.dog
  apiDomainName: my.monetr.dog
  allowSignUp: true
  enableWebhooks: true # Will be deprecated soon.
  beta:
    enableBetaCodes: true
  postgreSql:
    address: postgres.acceptance.monetr.in
    port: 5432
    database: monetr
  email:
    enabled: true
    domain: monetr.dev
    verification:
      enabled: true
      tokenLifetime: 30m
    smtp:
      username: apikey
      host: smtp.sendgrid.net
      port: 25
  sendGrid:
    enabled: false
    apiKey: ""
    templates:
      verifyEmailTemplate: ""
      forgotPasswordTemplate: ""
  reCaptcha:
    enabled: true
    verifyLogin: true
    verifyRegister: true
  plaid:
    environment: "https://development.plaid.com"
    enableReturningUserExperience: true
    webhooksEnabled: true
    webhooksDomain: my.monetr.dog
    oauthDomain: my.monetr.dog
  cors:
    allowedOrigins:
      - "https://my.monetr.dog"
    debug: false
  redis:
    enabled: true
    address: redis.redis.svc.cluster.local
    port: 6379
  logging:
    level: trace
  sentry:
    enabled: true
    sampleRate: 1.0
    traceSampleRate: 1.0
  vault:
    enabled: true
    address: "http://vault.internal.svc.cluster.local:8200"
    role: "monetr"
    insecureSkipVerify: false
    auth: "kubernetes"
    timeout: "30s"
    idleConnTimeout: "9m"
  stripe:
    enabled: true
    webhooksEnabled: true # Still working on this for now.
    billingEnabled: true
    initialPlan:
      freeTrialDays: 1
      stripePriceId: price_1JGYV0I4uGGnwpgw3kkur7ze
      features:
        - ManualBudgeting
        - LinkedBudgeting

