apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    name: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.2-alpine
          imagePullPolicy: Always
          ports:
            - name: rd
              containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    name: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: rd
      protocol: TCP
      name: rd
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
