apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}-api
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}

---
{{ if .Values.uiService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}-ui
  labels:
  {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "api.selectorLabels" . | nindent 4 }}
{{ end }}