name: Build

on:
  push:
    branches:
      - '!renovate/*'
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: containers.monetr.dev/rest-api
