name: Documentation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    container: ghcr.io/monetrapp/build-containers/ubuntu:20.04-2021.04.18
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: make dependencies
      - run: make docs
      - run: $GITHUB_WORKSPACE/node_modules/.bin/redoc-cli bundle $GITHUB_WORKSPACE/docs/swagger.yaml -o $GITHUB_WORKSPACE/docs/index.html
