name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    container: ghcr.io/monetr/build-containers/ubuntu:20.04-2021.05.01
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: make dependencies
      - run: make docs
      - run: $GITHUB_WORKSPACE/node_modules/.bin/redoc-cli bundle $GITHUB_WORKSPACE/docs/swagger.yaml -o $GITHUB_WORKSPACE/docs/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
