name: Build / Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    container: ghcr.io/monetrapp/build-containers/ubuntu:20.04-2021.04.18
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: make dependencies
      - run: make docs
