name: Environment

on:
  schedule:
    - cron: 0 17 * * * # Noon in central time.
  workflow_dispatch: { }

jobs:
  release-acceptance:
    name: Acceptance
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Acceptance
        run: git push origin $(go run github.com/monetr/rest-api/tools/releaser --since=-24h):acceptance
  release-dog:
    name: Dog Food
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Dog Food
        run: git push origin $(go run github.com/monetr/rest-api/tools/releaser --since=-24h):dog
  release-production:
    name: Production
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dog'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Production
        run: git push origin $(go run github.com/monetr/rest-api/tools/releaser --since=-48h):production
