name: Environment

on:
  schedule:
    - cron: 0 17 * * * # Noon in central time.
  workflow_dispatch: { }

jobs:
  release-acceptance:
    name: Acceptance
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Acceptance
        run: make push ENVIRONMENT=Acceptance
  release-dog:
    name: Dog Food
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Dog Food
        run: make push ENVIRONMENT=Dog
  release-production:
    name: Production
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dog'
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push To Production
        run: make push ENVIRONMENT=Production SINCE=48h
