name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.16
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: api-testing
          POSTGRES_DB: test-db
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_USER: api-testing
        POSTGRES_DB: test-db
