name: Build / Test

on:
  push:
    branches: [ main, staging, trying ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    container: golang:1.16.3
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: api-testing
      POSTGRES_DB: test-db
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: api-testing
          POSTGRES_DB: test-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: make dependencies
      - name: Build
        run: make build
      - name: Setup Schema
        run: make apply-schema-ci
      - name: Test
        run: make test
