name: Production

on:
  schedule:
    - cron: 0 17 * * * # Noon in central time.
  workflow_dispatch: { }

jobs:
  release-production:
    name: Production
    runs-on: ubuntu-latest
    container: golang:1.16.3
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: fetch
        run: git fetch --prune --unshallow
      - name: Push to production
        run: git push origin $(go run github.com/monetr/rest-api/tools/releaser):production
