name: Bot

on:
  push:
    branches:
      - main

jobs:
  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
          package-name: monetr

  build_ui:
    if: ${{ needs.release_please.outputs.release_created }}
    needs:
      - release_please
    name: Build UI
    runs-on: ubuntu-latest
    container: node:16.11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            $GITHUB_WORKSPACE/node_modules
          key: ${{ runner.os }}-ui-${{ hashFiles('$GITHUB_WORKSPACE/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-ui-${{ hashFiles('$GITHUB_WORKSPACE/yarn.lock') }}
            ${{ runner.os }}-ui-
      - name: Build
        run: |
          echo "${{ needs.release_please.outputs.version }}"
          make ui-dependencies
          RELEASE_VERSION=v${{ needs.release_please.outputs.version }} make build-ui
      - uses: actions/upload-artifact@v2
        with:
          name: '${{ needs.release_please.outputs.version }}-ui'
          path: '${{ github.workspace }}/pkg/ui/static/'
          retention-days: 7

  build_binary:
    if: ${{ needs.release_please.outputs.release_created }}
    needs:
      - release_please
      - build_ui
    name: Build Binary
    runs-on: ubuntu-latest
    container: ghcr.io/monetr/build-containers/golang:1.17.2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - darwin
        architecture:
          - amd64
          - arm64
        include:
          - os: windows
            architecture: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('$GITHUB_WORKSPACE/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('$GITHUB_WORKSPACE/go.sum') }}
            ${{ runner.os }}-go-
      - uses: actions/download-artifact@v2
        name: Download Compiled UI Artifacts
        with:
          name: '${{ needs.release_please.outputs.version }}-ui'
          path: '${{ github.workspace }}/pkg/ui/static/'
      - name: Build # I hate so much that I have to do this, but GitHub actions are awful at network connections.
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            RELEASE_VERSION=v${{ needs.release_please.outputs.version }} GOOS=${{ matrix.os }} GOARCH=${{ matrix.architecture }} make tar
      - uses: actions/upload-artifact@v2
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz'
          path: '${{ github.workspace }}/bin/monetr-v${{ needs.release_please.outputs.version }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz'
          retention-days: 7

  upload-artifacts:
    needs:
      - release_please
      - build_ui
      - build_binary
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download linux/amd64
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-linux-amd64.tar.gz'
          path: '/tmp/monetr-v${{ needs.release_please.outputs.version }}-linux-amd64.tar.gz'
      - uses: actions/download-artifact@v2
        name: Download linux/arm64
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-linux-arm64.tar.gz'
          path: '/tmp/monetr-v${{ needs.release_please.outputs.version }}-linux-arm64.tar.gz'
      - uses: actions/download-artifact@v2
        name: Download darwin/amd64
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-darwin-amd64.tar.gz'
          path: '/tmp/monetr-v${{ needs.release_please.outputs.version }}-darwin-amd64.tar.gz'
      - uses: actions/download-artifact@v2
        name: Download darwin/arm64
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-darwin-arm64.tar.gz'
          path: '/tmp/monetr-v${{ needs.release_please.outputs.version }}-darwin-arm64.tar.gz'
      - uses: actions/download-artifact@v2
        name: Download windows/amd64
        with:
          name: 'monetr-v${{ needs.release_please.outputs.version }}-windows-amd64.tar.gz'
          path: '/tmp/monetr-v${{ needs.release_please.outputs.version }}-windows-amd64.tar.gz'
      - name: Upload Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ needs.release_please.outputs.version }} /tmp/monetr-v${{ needs.release_please.outputs.version }}-linux-amd64.tar.gz --clobber
          gh release upload v${{ needs.release_please.outputs.version }} /tmp/monetr-v${{ needs.release_please.outputs.version }}-linux-arm64.tar.gz --clobber
          gh release upload v${{ needs.release_please.outputs.version }} /tmp/monetr-v${{ needs.release_please.outputs.version }}-darwin-amd64.tar.gz --clobber
          gh release upload v${{ needs.release_please.outputs.version }} /tmp/monetr-v${{ needs.release_please.outputs.version }}-darwin-arm64.tar.gz --clobber
          gh release upload v${{ needs.release_please.outputs.version }} /tmp/monetr-v${{ needs.release_please.outputs.version }}-windows-amd64.tar.gz --clobber

  container:
    if: ${{ needs.release_please.outputs.release_created }}
    needs:
      - "release_please"
      - "build_ui"
    name: Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/download-artifact@v2
        name: Download Compiled UI Artifacts
        with:
          name: '${{ needs.release_please.outputs.version }}-ui'
          path: '${{ github.workspace }}/pkg/ui/static/'
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: RELEASE=v${{ needs.release_please.outputs.version }},REVISION=${{ github.sha }}
          tags: |
            ghcr.io/monetr/monetr:latest
            ghcr.io/monetr/monetr:${{ needs.release_please.outputs.version }}
            monetr/monetr:latest
            monetr/monetr:${{ needs.release_please.outputs.version }}
