name: Daily Release

on:
  push:
    branches:
      - acceptance
  workflow_dispatch: { }

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'acceptance'
      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make release
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: rest-api
        with:
          environment: acceptance
