name: Bot

on:
  push:
    branches:
      - main

jobs:
  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
          package-name: monetr

  build_ui:
    if: ${{ needs.release_please.outputs.release_created }}
    needs:
      - release_please
    name: Build UI
    runs-on: ubuntu-latest
    container: node:16.11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            $GITHUB_WORKSPACE/node_modules
          key: ${{ runner.os }}-ui-${{ hashFiles('$GITHUB_WORKSPACE/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-ui-${{ hashFiles('$GITHUB_WORKSPACE/yarn.lock') }}
            ${{ runner.os }}-ui-
      - name: Build
        run: |
          echo "${{ needs.release_please.outputs.version }}"
          make ui-dependencies
          make build-ui
      - uses: actions/upload-artifact@v2
        with:
          name: '${{ github.sha }}-ui'
          path: '${{ github.workspace }}/pkg/ui/static/'
          retention-days: 7

  container:
    if: ${{ needs.release_please.outputs.release_created }}
    needs:
      - "release_please"
      - "build_ui"
    name: Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/download-artifact@v2
        name: Download Compiled UI Artifacts
        with:
          name: '${{ github.sha }}-ui'
          path: '${{ github.workspace }}/pkg/ui/static/'
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: RELEASE=v${{ needs.release_please.outputs.version }},REVISION=${{ github.sha }}
          tags: |
            ghcr.io/monetr/monetr:latest
            ghcr.io/monetr/monetr:${{ needs.release_please.outputs.version }}
            monetr/monetr:latest
            monetr/monetr:${{ needs.release_please.outputs.version }}
