name: Daily Release

on:
  push:
    branches:
      - acceptance
  workflow_dispatch: { }

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'acceptance'
      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make release
